### PR TITLE
No longer require parenthesis around multiline JSX blocks

### PR DESCRIPTION
**Pull request by naps62**

### CODE REVIEW

**Comment by naps62** [comment]
@gabrielpoca I was under the impression that we didn't want these?

**Comment by gabrielpoca** [comment]
@naps62 I don't want them. But it's the default of Airbnb's guide. My vote is to remove those. What does everyone else think? /cc @subvisual/developers

**Review by pfac — APPROVED** [review]
:+1: send those to hell

**Comment by gabrielpoca** [comment]
@subvisual/developers last call for comments everyone

**Review by frm — APPROVED** [review]

**Comment by frm** [comment]
@naps62 ping on this.

**Review by gabrielpoca — APPROVED** [review]

**Pull request merged**
